### ISSUE TITLE
Problem with version 0.54

### ISSUE THREAD

**Issue by solevi** [hellcatz/luckpool#61]
Hello,

I am facing problems while running latest 0.54 version. Previous version is working fine. OS is Windows Server 2019 Standard with all updates installed.
Version: 10.0.17763 Build 17763.

Tried both with and without `--ssl`, no difference.

Below is the log output:
```
D:\System>d:\System\hellminer\hellminer.exe --ssl -c stratum+tcp://eu.luckpool.net:3956#xnsub -u <REDACTED>.<REDACTED> -p x --cpu 6
----------------------------------------------------------------------
 Hellminer 0.54 [VerusHash 2.2 CPU Miner] Windows
----------------------------------------------------------------------
 * AMD Ryzen 7 3700X 8-Core Processor [8 Cores]
 * 2 Threads per Core
 * Supports AES
 * Supports AVX2
 * Supports SSE2

 * 16 Total CPU threads
 * 16 Usable threads based on CPU Affinity
----------------------------------------------------------------------
 * Miner Wallet Address: <REDACTED>
 * Worker Name: <REDACTED>
----------------------------------------------------------------------
Connecting to pool stratum+ssl://eu.luckpool.net:3956
----------------------------------------------------------------------
Using 6 cpu threads for mining
Unhandled Error
Traceback (most recent call last):
  File "site-packages\twisted\python\log.py", line 96, in callWithLogger

  File "site-packages\twisted\python\log.py", line 80, in callWithContext

  File "site-packages\twisted\python\context.py", line 117, in callWithContext

  File "site-packages\twisted\python\context.py", line 82, in callWithContext

--- <exception caught here> ---
  File "site-packages\twisted\internet\selectreactor.py", line 148, in _doReadOrWrite

  File "site-packages\twisted\internet\tcp.py", line 615, in doConnect

  File "site-packages\twisted\internet\tcp.py", line 643, in _connectDone

  File "site-packages\twisted\protocols\tls.py", line 217, in makeConnection

  File "site-packages\twisted\protocols\policies.py", line 75, in makeConnection

  File "site-packages\twisted\internet\protocol.py", line 509, in makeConnection

  File "hellminer", line 75, in connectionMade

  File "hellminer", line 381, in startSolvers

  File "hellminer", line 398, in startSolver

  File "site-packages\twisted\internet\posixbase.py", line 417, in spawnProcess

  File "site-packages\twisted\internet\_dumbwin32proc.py", line 202, in __init__

builtins.OSError: (2, 'CreateProcess', 'The system cannot find the file specified.')

Pool set extra nonce 00000000
Pool set share target 0000000000000000000000000000000000000000000000000000000000000000
Pool set job id 0000 [solution: 06, clean: True]
Unhandled Error
Traceback (most recent call last):
  File "hellminer", line 699, in main

  File "site-packages\twisted\internet\base.py", line 1315, in run

  File "site-packages\twisted\internet\base.py", line 1328, in mainLoop

  File "site-packages\twisted\internet\selectreactor.py", line 142, in doSelect

--- <exception caught here> ---
  File "site-packages\twisted\python\log.py", line 96, in callWithLogger

  File "site-packages\twisted\python\log.py", line 80, in callWithContext

  File "site-packages\twisted\python\context.py", line 117, in callWithContext

  File "site-packages\twisted\python\context.py", line 82, in callWithContext

  File "site-packages\twisted\internet\selectreactor.py", line 153, in _doReadOrWrite

  File "site-packages\twisted\internet\posixbase.py", line 303, in _disconnectSelectable

  File "site-packages\twisted\internet\tcp.py", line 509, in connectionLost

  File "site-packages\twisted\internet\base.py", line 1204, in connectionLost

  File "site-packages\twisted\protocols\policies.py", line 152, in clientConnectionLost

  File "hellminer", line 197, in clientConnectionLost

  File "hellminer", line 415, in setJobParams

  File "hellminer", line 301, in setJobParams

builtins.AttributeError: 'NoneType' object has no attribute 'write'

----------------------------------------------------------------------
No solver threads running! CPU may be incompatible ...
----------------------------------------------------------------------
----------------------------------------------------------------------
No solver threads running! CPU may be incompatible ...
----------------------------------------------------------------------

```

**Comment by solevi** [comment]
Hello,
Similar problem with Ubuntu 22.04 LTS:
```
# uname -a
Linux <REDACTED> 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

# /usr/local/hellminer/hellminer -c stratum+tcp://na.luckpool.net:3956#xnsub -u <REDACTED>.<REDACTED> -p x --cpu 16 &

----------------------------------------------------------------------
 Hellminer 0.54 [VerusHash 2.2 CPU Miner] Linux
----------------------------------------------------------------------
 * Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
 * Supports AES
 * Supports AVX2
 * Supports SSE2
 
 * 32 Total CPU threads
 * 14 Usable threads based on CPU Affinity
----------------------------------------------------------------------
 * Miner Wallet Address: <REDACTED>
 * Worker Name: <REDACTED>
----------------------------------------------------------------------
Connecting to pool stratum+tcp://na.luckpool.net:3956
----------------------------------------------------------------------
Using 16 cpu threads for mining
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 407 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
errReceived! with 408 bytes!
Pool set extra nonce bfc28832
Pool authorized miner <REDACTED>.<REDACTED>
Pool set share target 0000004000000000000000000000000000000000000000000000000000000000
Pool set job id 4e4d567 [solution: 06, clean: True]
Pool accepted extra nonce subscription
----------------------------------------------------------------------
No solver threads running! CPU may be incompatible ...
----------------------------------------------------------------------
Pool set job id 4e4d568 [solution: 06, clean: True] 
```
